/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PiRouteImport } from './routes/pi'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MasterSpecsRouteImport } from './routes/master-specs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FreeGuideRouteImport } from './routes/free-guide'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DemoExpiredRouteImport } from './routes/demo-expired'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgTeamRouteImport } from './routes/org.team'
import { Route as MaterialIdRouteImport } from './routes/material.$id'
import { Route as ConsoleLoginRouteImport } from './routes/console.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSpecsRoute = MasterSpecsRouteImport.update({
  id: '/master-specs',
  path: '/master-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeGuideRoute = FreeGuideRouteImport.update({
  id: '/free-guide',
  path: '/free-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoExpiredRoute = DemoExpiredRouteImport.update({
  id: '/demo-expired',
  path: '/demo-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamRoute = OrgTeamRouteImport.update({
  id: '/org/team',
  path: '/org/team',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleLoginRoute = ConsoleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConsoleRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo-expired': typeof DemoExpiredRoute
  '/documents': typeof DocumentsRoute
  '/engineer': typeof EngineerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-guide': typeof FreeGuideRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-specs': typeof MasterSpecsRoute
  '/orders': typeof OrdersRoute
  '/pi': typeof PiRoute
  '/procurement': typeof ProcurementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/console/login': typeof ConsoleLoginRoute
  '/material/$id': typeof MaterialIdRoute
  '/org/team': typeof OrgTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo-expired': typeof DemoExpiredRoute
  '/documents': typeof DocumentsRoute
  '/engineer': typeof EngineerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-guide': typeof FreeGuideRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-specs': typeof MasterSpecsRoute
  '/orders': typeof OrdersRoute
  '/pi': typeof PiRoute
  '/procurement': typeof ProcurementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/console/login': typeof ConsoleLoginRoute
  '/material/$id': typeof MaterialIdRoute
  '/org/team': typeof OrgTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/demo-expired': typeof DemoExpiredRoute
  '/documents': typeof DocumentsRoute
  '/engineer': typeof EngineerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-guide': typeof FreeGuideRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-specs': typeof MasterSpecsRoute
  '/orders': typeof OrdersRoute
  '/pi': typeof PiRoute
  '/procurement': typeof ProcurementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/console/login': typeof ConsoleLoginRoute
  '/material/$id': typeof MaterialIdRoute
  '/org/team': typeof OrgTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/compliance'
    | '/console'
    | '/dashboard'
    | '/demo-expired'
    | '/documents'
    | '/engineer'
    | '/forgot-password'
    | '/free-guide'
    | '/inventory'
    | '/login'
    | '/master-specs'
    | '/orders'
    | '/pi'
    | '/procurement'
    | '/reset-password'
    | '/settings'
    | '/suppliers'
    | '/admin/organizations'
    | '/admin/users'
    | '/console/login'
    | '/material/$id'
    | '/org/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/compliance'
    | '/console'
    | '/dashboard'
    | '/demo-expired'
    | '/documents'
    | '/engineer'
    | '/forgot-password'
    | '/free-guide'
    | '/inventory'
    | '/login'
    | '/master-specs'
    | '/orders'
    | '/pi'
    | '/procurement'
    | '/reset-password'
    | '/settings'
    | '/suppliers'
    | '/admin/organizations'
    | '/admin/users'
    | '/console/login'
    | '/material/$id'
    | '/org/team'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/compliance'
    | '/console'
    | '/dashboard'
    | '/demo-expired'
    | '/documents'
    | '/engineer'
    | '/forgot-password'
    | '/free-guide'
    | '/inventory'
    | '/login'
    | '/master-specs'
    | '/orders'
    | '/pi'
    | '/procurement'
    | '/reset-password'
    | '/settings'
    | '/suppliers'
    | '/admin/organizations'
    | '/admin/users'
    | '/console/login'
    | '/material/$id'
    | '/org/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DemoExpiredRoute: typeof DemoExpiredRoute
  DocumentsRoute: typeof DocumentsRoute
  EngineerRoute: typeof EngineerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreeGuideRoute: typeof FreeGuideRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MasterSpecsRoute: typeof MasterSpecsRoute
  OrdersRoute: typeof OrdersRoute
  PiRoute: typeof PiRoute
  ProcurementRoute: typeof ProcurementRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MaterialIdRoute: typeof MaterialIdRoute
  OrgTeamRoute: typeof OrgTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-specs': {
      id: '/master-specs'
      path: '/master-specs'
      fullPath: '/master-specs'
      preLoaderRoute: typeof MasterSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-guide': {
      id: '/free-guide'
      path: '/free-guide'
      fullPath: '/free-guide'
      preLoaderRoute: typeof FreeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-expired': {
      id: '/demo-expired'
      path: '/demo-expired'
      fullPath: '/demo-expired'
      preLoaderRoute: typeof DemoExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team': {
      id: '/org/team'
      path: '/org/team'
      fullPath: '/org/team'
      preLoaderRoute: typeof OrgTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/login': {
      id: '/console/login'
      path: '/login'
      fullPath: '/console/login'
      preLoaderRoute: typeof ConsoleLoginRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleLoginRoute: typeof ConsoleLoginRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleLoginRoute: ConsoleLoginRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ComplianceRoute: ComplianceRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DemoExpiredRoute: DemoExpiredRoute,
  DocumentsRoute: DocumentsRoute,
  EngineerRoute: EngineerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreeGuideRoute: FreeGuideRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MasterSpecsRoute: MasterSpecsRoute,
  OrdersRoute: OrdersRoute,
  PiRoute: PiRoute,
  ProcurementRoute: ProcurementRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  MaterialIdRoute: MaterialIdRoute,
  OrgTeamRoute: OrgTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
