/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PiRouteImport } from './routes/pi'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MasterSpecsRouteImport } from './routes/master-specs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialIdRouteImport } from './routes/material.$id'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterSpecsRoute = MasterSpecsRouteImport.update({
  id: '/master-specs',
  path: '/master-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRoute
  '/documents': typeof DocumentsRoute
  '/engineer': typeof EngineerRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-specs': typeof MasterSpecsRoute
  '/orders': typeof OrdersRoute
  '/pi': typeof PiRoute
  '/procurement': typeof ProcurementRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/material/$id': typeof MaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRoute
  '/documents': typeof DocumentsRoute
  '/engineer': typeof EngineerRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-specs': typeof MasterSpecsRoute
  '/orders': typeof OrdersRoute
  '/pi': typeof PiRoute
  '/procurement': typeof ProcurementRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/material/$id': typeof MaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRoute
  '/documents': typeof DocumentsRoute
  '/engineer': typeof EngineerRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-specs': typeof MasterSpecsRoute
  '/orders': typeof OrdersRoute
  '/pi': typeof PiRoute
  '/procurement': typeof ProcurementRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/material/$id': typeof MaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/console'
    | '/documents'
    | '/engineer'
    | '/inventory'
    | '/login'
    | '/master-specs'
    | '/orders'
    | '/pi'
    | '/procurement'
    | '/settings'
    | '/suppliers'
    | '/material/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/console'
    | '/documents'
    | '/engineer'
    | '/inventory'
    | '/login'
    | '/master-specs'
    | '/orders'
    | '/pi'
    | '/procurement'
    | '/settings'
    | '/suppliers'
    | '/material/$id'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/console'
    | '/documents'
    | '/engineer'
    | '/inventory'
    | '/login'
    | '/master-specs'
    | '/orders'
    | '/pi'
    | '/procurement'
    | '/settings'
    | '/suppliers'
    | '/material/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsoleRoute: typeof ConsoleRoute
  DocumentsRoute: typeof DocumentsRoute
  EngineerRoute: typeof EngineerRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MasterSpecsRoute: typeof MasterSpecsRoute
  OrdersRoute: typeof OrdersRoute
  PiRoute: typeof PiRoute
  ProcurementRoute: typeof ProcurementRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  MaterialIdRoute: typeof MaterialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-specs': {
      id: '/master-specs'
      path: '/master-specs'
      fullPath: '/master-specs'
      preLoaderRoute: typeof MasterSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  ConsoleRoute: ConsoleRoute,
  DocumentsRoute: DocumentsRoute,
  EngineerRoute: EngineerRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MasterSpecsRoute: MasterSpecsRoute,
  OrdersRoute: OrdersRoute,
  PiRoute: PiRoute,
  ProcurementRoute: ProcurementRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  MaterialIdRoute: MaterialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
